version: '1.0.0'

services:
  db:
    image: mongo
    restart: always
    ports: 
      - '27017:27017'
    commond: '--smallfiles --logpath=/dev/null 2>&1'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword1234
  web:
    build: .
    image: myapp:v1
    # 使用 command 可以覆盖容器启动后默认执行的命令。
    # command: npm run 
    # args 表示参数 也就是 node
    # args: 
    # Compose 的容器名称格式是：<项目名称><服务名称><序号>
    # container_name: app
    # 容器的依赖
    depends_on: 
      - db
    volumes:
      - .:/myapp
    # expose只是指定暴露的端口 实际端口映射还是需要ports
    expose:
      - "7001"
    ports:
      - "7001:7001"
    # 这个标签解决的是容器连接问题
    links:
      - db
    environment:
      PORT: 7001
      NODE_ENV: production
